logging:
  pattern:
    console:

spring:
  application:
    name: my-weather-server
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 0.0.1

